version: 2

models:
  - name: fact_listings
    columns:
      - name: listing_key
        tests: [unique, not_null]
      - name: location_key
        tests: [not_null]
      - name: property_key
        tests: [not_null]
      - name: price_egp
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

  - name: dim_location
    columns:
      - name: location_key
        tests: [unique, not_null]
      - name: source_location_id
        tests: [unique, not_null]

  - name: dim_agent
    columns:
      - name: agent_key
        tests: [unique, not_null]

  - name: dim_property
    columns:
      - name: property_key
        tests: [unique, not_null]

  - name: dim_listing_flags
    columns:
      - name: flags_key
        tests: [unique, not_null]